myproject/gestorbases/urls.py
from django.contrib import admin
from django.urls import path
from myproject.gestorbases import views

app_name='gestorbases'

urlpatterns = [
	#path('', views.home, name='home'),
	path('', views.dashboard, name='dashboard'),


	path('bases/nova', views.BaseCreateView.as_view(), name='nova_base'),
	#path('bases/lista', views.BaseListView.as_view(), name='lista_bases'),
	path('bases/lista', views.listingBases, name='lista_bases'),
	path('bases/atualiza/<pk>', views.BaseUpdateView.as_view(), name='atualiza_base'),
	path('bases/exclui/<pk>', views.BaseDeleteView.as_view(), name='exclui_base'),


	path('tabelas/nova', views.TabelaCreateView.as_view(), name='nova_tabela'),
	#path('tabelas/lista', views.TabelaListView.as_view(), name='lista_tabelas'),
	path('tabelas/lista', views.listingTables, name='lista_tabelas'),
	path('tabelas/atualiza/<pk>', views.TabelaUpdateView.as_view(), name='atualiza_tabela'),
	path('tabelas/exclui/<pk>', views.TabelaDeleteView.as_view(), name='exclui_tabela'),


	#path('atualizacoes/nova', views.AtualizacaoCreateView.as_view(), name='nova_atualizacao'),
	path('atualizacoes/nova2/<pk>,<tab_nome>', views.novaAtualizazao, name='nova_atualizacao2'),
	path('atualizacoes/nova/<pk>', views.AtualizacaoCreateView2.as_view(), name='nova_atualizacao3'),

	#path('atualizacoes/lista', views.AtualizacaoListView.as_view(), name='lista_atualizacoes'),
	path('atualizacoes/lista', views.listingAtualizacoes, name='lista_atualizacoes'),
	path('atualizacoes/detalhes/<pk>', views.AtualizacaoDetalhesView.as_view(), name='detalhes_atualizacao'),
	path('atualizacoes/atualiza/<pk>', views.AtualizacaoUpdateView.as_view(), name='atualiza_atualizacao'),
	path('atualizacoes/exclui/<pk>', views.AtualizacaoDeleteView.as_view(), name='exclui_atualizacao'),

	path('atualizacoes/chart', views.getAtualizacoes, name='atualizacoes_chart'),

	path('login/', views.login, name='login'),
	path('sair/', views.sair, name='sair'),

    path('admin/', admin.site.urls),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('core/', include('myproject.core.urls', namespace='core')),

    path('website/', include('myproject.website.urls', namespace='website')),

    path('gestorbases/', include('myproject.gestorbases.urls', namespace='gestorbases'))
]

myproject/website/urls.py
from myproject.website.views import IndexTemplateView, FuncionarioListView, FuncionarioUpdateView, FuncionarioCreateView, \
    FuncionarioDeleteView

from django.urls import path

from myproject.website import views

app_name = 'website'

urlpatterns = [
    # GET /
    path('', IndexTemplateView.as_view(), name="index"),

    # GET /funcionario/cadastrar
    path('funcionario/cadastrar', FuncionarioCreateView.as_view(), name="cadastra_funcionario"),

    # GET /funcionarios
    #path('funcionarios/', FuncionarioListView.as_view(), name="lista_funcionarios"),

    path('funcionarios/', views.listing, name='lista_funcionarios'),

    # GET/POST /funcionario/{pk}
    path('funcionario/<pk>', FuncionarioUpdateView.as_view(), name="atualiza_funcionario"),

    # GET/POST /funcionarios/excluir/{pk}
    path('funcionario/excluir/<pk>', FuncionarioDeleteView.as_view(), name="deleta_funcionario"),
]

myproject/gestorbases/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Base(models.Model):
    nome = models.CharField(max_length=255, null=False, blank=False)
    descricao = models.TextField(null=True, blank=False)
    atualizacao = models.DateField('Data de atualizacao', null=True, blank=True)
    host = models.CharField(max_length=255, null=True, blank=False)
    owner = models.CharField(max_length=255, null=True, blank=True)
    objetos = models.Manager()

    def __str__(self):
        return self.nome


class Tabela(models.Model):
    base = models.ForeignKey(Base, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, null=True, blank=False)
    descricao = models.TextField(max_length=255, null=True, blank=True)
    esquema = models.CharField(max_length=255, null=True, blank=True)
    objetos = models.Manager()

    def __str__(self):
        return self.nome
     


class Atualizacao(models.Model):
    tabela = models.ForeignKey(Tabela, on_delete=models.CASCADE)
    data_atualizacao = models.DateField('Data da atualizacao', auto_now_add=True)
    responsavel = models.CharField(max_length=255, null=False, blank=False)
    observacoes = models.TextField(null=True, blank=True)
    mes_ref = models.IntegerField(null=True, blank=True)
    ano_ref = models.IntegerField(null=True, blank=True)
    origem_dados = models.CharField(max_length=255, null=True, blank=False)
    objetos = models.Manager()

    def __str__(self):
        return self.tabela.nome

      

myproject/gestorbases/forms.py
from django import forms
from myproject.gestorbases.models import Base, Tabela , Atualizacao


# FORMULÁRIO DE INCLUSÃO DE BASES
# -------------------------------------------
class InsereBaseForm(forms.ModelForm):
	
	class Meta:
		# Modelo 
		model = Base
		# Campos que estarão no form
		fields = ['nome', 'descricao', 'atualizacao', 'host', 'owner']


class InsereTabelaForm(forms.ModelForm):
    class Meta:
        # Modelo
        model = Tabela
        # Campos que estarão no form
        fields = ['base', 'nome', 'descricao', 'esquema']


class InsereAtualizacaoForm(forms.ModelForm):
    class Meta:
        # Modelo
        model = Atualizacao
        # Campos que estarão no fomr
        fields = ['tabela', 'responsavel', 'observacoes', 'mes_ref', 'ano_ref', 'origem_dados']


    def filteringTables(request):
        tabela = request.GET.get('tabela')
        tabelas = Tabela.objetos.filter(nome__icontains=tabela)
        return tabelas

        

myproject/gestorbases/views.py
# DEPENDÊNCIAS NECESSÁRIAS PARA REDIRECIONAR E RENDERIZAR TEMPLATES
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import HttpResponse


# DEPENDÊNCIAS NECESSÁRIAS PARA TEMPLATES
from django.views.generic import TemplateView
from django.views.generic import ListView
from django.views.generic import UpdateView
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import View

# IMPORTANDO OS FORMS DA APLICAÇÃO
from myproject.gestorbases.forms import InsereBaseForm
from myproject.gestorbases.forms import InsereTabelaForm
from myproject.gestorbases.forms import InsereAtualizacaoForm

# IMPORTANDO OS MODELS DA APLICAÇÃO
from myproject.gestorbases.models import Base
from myproject.gestorbases.models import Tabela
from myproject.gestorbases.models import Atualizacao

# DEPENDÊNCIAS NECESSÁRIAS PARA IMPLEMENTAR A PAGINAÇÃO
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from django.core.paginator import Paginator

# DEPENDÊNCIAS NECESSÁRIAS PARA IMPLEMENTAR A LOGIN
from django.contrib.auth import authenticate, logout, login as authlogin
from django.shortcuts import render_to_response
from django.template import Context, loader, RequestContext
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

# DEPENDÊNCIAS NECESSÁRIAS PARA SERIALIZAR DADOS EM JSON
import json



# ########################### VIEWS DE LOGIN ##########################
def login(request):
	if request.user.id:
		return render(request, 'gestorbases/logado.html',{})
	if request.POST:
		usuario = request.POST.get('usuario')
		senha = request.POST.get('senha')
		u = authenticate(request, username=usuario, password=senha)

		if(u is not None):
			if(u.is_active):
				authlogin(request, u)
				return redirect('gestorbases:dashboard')
				#return render(request, 'gestorbases/dashboard.html',{'user': u})
	return render(request, 'gestorbases/login.html', {})

def sair(request):
	logout(request)
	return render(request, 'gestorbases/login.html', {})
# ########################### SISTEMA DE LOGIN ##########################


# RENDERIZAR O DASHBOARD
@login_required
def dashboard(request):
	if request.user.is_authenticated:
		bases = Base.objetos.all()
		tabelas = Tabela.objetos.all()
		atualizacoes = Atualizacao.objetos.all()
		contexto = {'tabelas': tabelas, 'bases': bases, 'atualizacoes': atualizacoes}
		return render(request, 'gestorbases/dashboard.html', contexto)


# CADASTRAMENTO DE BASE
# ----------------------------------------------
class BaseCreateView(LoginRequiredMixin, CreateView):
    template_name = 'gestorbases/base/cadastroBase.html'
    model = Base
    form_class = InsereBaseForm
    success_url = reverse_lazy("gestorbases:lista_bases")



# LISTAGEM DE BASES COM PAGINAÇÃO
# ----------------------------------------------
@login_required
def listingBases(request):
	bases_lista = Base.objetos.all().order_by('id')
	paginator = Paginator(bases_lista, 7)
	page = request.GET.get('page')
	bases = paginator.get_page(page)
	return render(request, 'gestorbases/base/listaBases.html', {'bases':bases})

# ATUALIZAÇÃO DE BASE
# ----------------------------------------------
class BaseUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'gestorbases/base/editaBase.html'
	model = Base
	fields = '__all__'
	context_object_name = 'base'
	success_url = reverse_lazy("gestorbases:lista_bases")


# EXCLUSÃO DE BASE
# ----------------------------------------------
class BaseDeleteView(LoginRequiredMixin, DeleteView):
	template_name = 'gestorbases/base/excluiBase.html'
	model = Base
	fields = '__all__'
	context_object_name = 'base'
	success_url = reverse_lazy('gestorbases:lista_bases')



# CADASTRO DE TABELA
# ----------------------------------------------
class TabelaCreateView(LoginRequiredMixin, CreateView):
	template_name = 'gestorbases/tabela/cadastroTabela.html'
	model = Tabela
	form_class = InsereTabelaForm
	success_url = reverse_lazy('gestorbases:lista_tabelas')


# LISTAGEM DE TABELAS COM PAGINAÇÃO
# ----------------------------------------------
@login_required
def listingTables(request):
	if request.GET.get('tabela') == None:
		tabelas_lista = Tabela.objetos.all()[:100]
		paginator = Paginator(tabelas_lista, 7)
		page = request.GET.get('page')
		tabelas = paginator.get_page(page)
		return render(request, 'gestorbases/tabela/listaTabelas.html', {'tabelas': tabelas})
	else:
		tab = request.GET.get('tabela')
		tabelas_lista = Tabela.objetos.filter(nome__icontains=tab)[:100]
		paginator = Paginator(tabelas_lista, 7)
		page = request.GET.get('page')
		tabelas = paginator.get_page(page)
		return render(request, 'gestorbases/tabela/listaTabelas.html', {'tabelas': tabelas})



# EDIÇÃO DE TABELAS
# ----------------------------------------------
class TabelaUpdateView(LoginRequiredMixin, UpdateView):
	template_name = 'gestorbases/tabela/editaTabela.html'
	models = Tabela
	fields = '__all__'
	context_object_name = 'tabela'
	success_url = reverse_lazy('gestorbases:lista_tabelas')


	def get_object(self, queryset=None):
		tabela = None
		id = self.kwargs.get(self.pk_url_kwarg)
		if id is not None:
			# Busca o tabela apartir do id
			tabela = Tabela.objetos.filter(id=id).first()

		# Retorna o objeto encontrado
		return tabela
		

# EXCLUSÃO DE TABELA
# ----------------------------------------------
class TabelaDeleteView(LoginRequiredMixin, DeleteView):
	template_name = 'gestorbases/tabela/excluiTabela.html'
	model = Tabela
	fields = '__all__'
	context_object_name = 'tabela'
	success_url = reverse_lazy('gestorbases:lista_tabelas')



# REGISTRO DE NOVA ATUALIZAÇÃO
# ----------------------------------------------

class AtualizacaoCreateView(LoginRequiredMixin, CreateView):
	template_name = 'gestorbases/atualizacao/cadastroAtualizacao.html'
	model = Atualizacao
	InsereAtualizacaoForm.tabela = Tabela.objetos.all()[:5]
	form_class = InsereAtualizacaoForm
	success_url = reverse_lazy('gestorbases:nova_atualizacao')



def novaAtualizazao(request, pk, tab_nome):
	if request.POST:
		tabela_id = request.POST.get('tabela')
		tabela = Tabela.objetos.filter(id=tabela_id).first()
		responsavel = request.POST.get('responsavel')
		origem_dados = request.POST.get('origem_dados')
		mes_ref = request.POST.get('mes_ref')
		ano_ref = request.POST.get('ano_ref')
		observacao = request.POST.get('observacao')
		atualizacao = Atualizacao(tabela=tabela, responsavel=responsavel, observacoes=observacao, mes_ref=mes_ref, ano_ref=ano_ref, origem_dados=origem_dados)
		atualizacao.save()
		return redirect('gestorbases:lista_atualizacoes')
	else:
		context = {
			'tabela': tab_nome, 'pk':pk
		}
		return render(request, 'gestorbases/atualizacao/novaAtualizacao.html', context)

class AtualizacaoCreateView2(LoginRequiredMixin, CreateView):
	template_name = 'gestorbases/atualizacao/novaAtualizacao.html'
	model = Atualizacao
	InsereAtualizacaoForm.tabela = Tabela.objetos.all()[:5]
	form_class = InsereAtualizacaoForm
	success_url = reverse_lazy('gestorbases:nova_atualizacao')

	def get_object(self, queryset=None):
		tabela = None
		id = self.kwargs.get(self.pk_url_kwarg)
		if id is not None:
			tabela = Tabela.objetos.filter(id=id).first()
		return tabela


# FAZ PAGINAÇÃO DE ATUALIZAÇÃO
# ----------------------------------------------
@login_required
def listingAtualizacoes(request):
	if request.GET.get('tabela') != None and request.GET.get('data') != None:
		tab = request.GET.get('tabela')
		date = request.GET.get('data')
		atualizacoes = getUpdateByTableAndDate(request, tab, date)
		contexto = {'atualizacoes': atualizacoes, 'nomeTabela':tab, 'data':date}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	elif request.GET.get('tabela') != None:
		tab = request.GET.get('tabela')
		atualizacoes = getUpdateByTables(request, tab)
		contexto = {'atualizacoes': atualizacoes, 'nomeTabela':tab}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	elif request.GET.get('tabela') == None:		
		atualizacoes = getAllUpdates(request)
		contexto = {'atualizacoes': atualizacoes}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	else:
		tab = request.GET.get('tabela')
		date = request.GET.get('data')
		atualizacoes = getUpdateByTableAndDate(request, tab, date)
		#atualizacoes = getUpdateByTables(request, tab)
		contexto = {'atualizacoes': atualizacoes, 'nomeTabela':tab, 'data':date}
		return render(request, 'gestorbases/atualizacao/listaAtualizacoes.html', contexto)
	

def getAllUpdates(request):
	atualizacoes_lista = Atualizacao.objetos.all().order_by('pk')
	paginator = Paginator(atualizacoes_lista, 5)
	page = request.GET.get('page')
	return paginator.get_page(page)

def getUpdateByTables(request, tab):
	tabelas = Tabela.objetos.filter(nome__icontains=tab)
	condicao = ''
	for tabela in tabelas:
		if condicao != '':
			condicao = condicao + ', ' + str(tabela.id)
		else:
			condicao = condicao + str(tabela.id)
	condicao = "(" + condicao + ")"
	if condicao == '()':
		condicao = '(-1)'
	atualizacoes_lista = Atualizacao.objetos.raw("select * from gestorbases_atualizacao where tabela_id in " + condicao)
	paginator = Paginator(atualizacoes_lista, 5)
	page = request.GET.get('page')
	return paginator.get_page(page)



def getAtualizacoes(request):
	from django.db import connection
	atualizacoes = []
	cursor = connection.cursor()
	cursor.execute("select to_char(data_atualizacao, 'DD/MM/yyyy'), count(*) from gestorbases_atualizacao where data_atualizacao > current_date - INTERVAL '365 DAYS' group by data_atualizacao order by data_atualizacao")
	for atualizacao in cursor:
		atualizacoes.append(atualizacao)


	if request.is_ajax():
		contexto = {'atualizacoes':atualizacoes}

myproject/gestorbases/templates/gestorbases/atualizacao/cadastroAtualizacao.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}

{% block titulo_conteudo %}Nova Atualização {% endblock %}

{% block conteudo %}

  <div class="container-fluid">
    <!--
    <div class="alert  alert-danger  alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <i class="fa  fa-exclamation-circle"></i> Já existe um produto com o nome informado.
    </div>
  -->

    <form method="post" >
      <!-- Não se esqueça dessa tag -->
            {% csrf_token %}
      
      	<div class="row">
        <div class="col-sm-6">
          	<div class="form-group">
	            <label for="input-base-host">Tabela</label>
	            {% render_field form.tabela class+="form-control" %}
          	</div>
        </div>
	        <div class="col-sm-6">
	          	<div class="form-group">
		            <label for="input-base-host">Responsável atualização</label>
		            {% render_field form.responsavel class+="form-control" %}
	          	</div>
	        </div>
      	</div>

      	<div class="row">
	        <div class="col-sm-4">
	          	<div class="form-group">
		            <label for="input-base-host">Origem Dados</label>
		            {% render_field form.origem_dados class+="form-control" %}
	          	</div>
	        </div>
	        <div class="col-sm-4">
	          	<div class="form-group">
		            <label for="input-base-host">Mês Referência</label>
		            {% render_field form.mes_ref class+="form-control" %}
	          	</div>
	        </div>
	        <div class="col-sm-4">
	          	<div class="form-group">
		            <label for="input-base-host">Ano Referência</label>
		            {% render_field form.ano_ref class+="form-control" %}
	          	</div>
	        </div>
      	</div>     

      <div class="form-group">
        <label for="input-base-descricao">Observações</label>
        {% render_field form.observacoes class+="form-control" rows="2" %}
      </div>
      
      <div class="form-group">
        <button class="btn  btn-primary" type="submit">Salvar</button>
        <a href="{% url 'gestorbases:lista_atualizacoes' %}" class="btn  btn-default">Cancelar</a>
        <!--
        <a href="#" class="btn  btn-link  aw-btn-link-danger">Excluir este produto</a>   onclick="excluir() -->
      </div>
    </form>
  </div>


{% endblock %}
	

myproject/gestorbases/templates/gestorbases/atualizacao/detalhesAtualizacao.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}


{% load static %}

{% block titulo_conteudo %}Detalhes Atualização {% endblock %}

{% block opcoes %}
    
{% endblock %}

{% block conteudo %}

    <div class="card" style="border: 1px solid #1E94D2;
        								border-radius: 5px;
        								padding: 2%; box-shadow: 5px 5px 8px #888888;">
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bold;">{{ atualizacao }}</h5>
        <hr />
        <div class="form-group" style="border-radius: 5px;
        								padding: 2%;  ">
          <label for="input-base-nome">Tabela: </label>
          {{atualizacao.tabela}}
          <br/>
          <label for="input-base-nome">Data Atualização: </label>
          {{atualizacao.data_atualizacao}}
          <br/>
          <label for="input-base-nome">Origem Dados: </label>
          {{atualizacao.origem_dados}}
          <br/>
          <label for="input-base-nome">Ano de Referência: </label>
          {{atualizacao.ano_ref}}
          <br/>
          <label for="input-base-nome">Mês de Referência: </label>
          {{atualizacao.mes_ref}}
          <br/>
          <label for="input-base-nome">Responsável: </label>
          {{atualizacao.responsavel}}
          <br/>
          <label for="input-base-nome">Observações: </label>
          {{atualizacao.observacoes}}
        </div>
      </div>

      <form method="post">
          {% csrf_token %}
          <hr />
          <div class="text-right">
            <a href="{% url 'gestorbases:lista_atualizacoes' %}" 
              class="btn btn-outline-danger">
                Voltar
            </a>
            <a href="{% url 'gestorbases:atualiza_atualizacao' pk=atualizacao.id %}" 
              class="btn btn-outline-danger">
                Editar atualização
            </a>
          </div>
        </form>
    </div>


<!-- 
    <div class="container mt-5">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Exclusão de Funcionário</h5>

        <p class="card-text">
          Você tem certeza que quer excluir o funcionário 
          <b>{{ funcionario.nome }}</b>?
        </p>

        <form method="post">
          {% csrf_token %}

          <hr />
          <div class="text-right">
            <a href="{% url 'website:lista_funcionarios' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  -->
{% endblock %}

myproject/gestorbases/templates/gestorbases/atualizacao/excluiAtualizacao.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}


{% load static %}

{% block titulo_conteudo %}Excluir Registro de atualização {% endblock %}

{% block opcoes %}
    
{% endblock %}

{% block conteudo %}

    <div class="card" style="border: 1px solid #1E94D2;
        								border-radius: 5px;
        								padding: 2%; box-shadow: 5px 5px 8px #888888;">
      <div class="card-body">
        <h5 class="card-title" style="font-weight: bold;">Tem certeza que quer excluir este registro?</h5>
        <hr />
        <div class="form-group" style="border-radius: 5px;
        								padding: 2%;  ">
          <label for="input-base-nome">Tabela: </label>
          {{atualizacao.tabela}}
          <br/>
          <label for="input-base-nome">Data Atualização: </label>
          {{atualizacao.data_atualizacao}}
          <br/>
          <label for="input-base-nome">Origem Dados: </label>
          {{atualizacao.origem_dados}}
          <br/>
          <label for="input-base-nome">Ano de Referência: </label>
          {{atualizacao.ano_ref}}
          <br/>
          <label for="input-base-nome">Mês de Referência: </label>
          {{atualizacao.mes_ref}}
          <br/>
          <label for="input-base-nome">Responsável: </label>
          {{atualizacao.responsavel}}
          <br/>
          <label for="input-base-nome">Observações: </label>
          {{atualizacao.observacoes}}
        </div>
      </div>

      <form method="post">
          {% csrf_token %}
          <hr />
          <div class="text-right">
            <a href="{% url 'gestorbases:lista_atualizacoes' %}" 
              class="btn btn-outline-danger">
                Cancelar
            </a>
            <button class="btn btn-danger">Excluir</button>
          </div>
        </form>
    </div>
{% endblock %}

myproject/gestorbases/templates/gestorbases/atualizacao/listaAtualizacoes.html
{% extends "gestorbases/_layouts/base.html" %}

{% load widget_tweaks %}

{% load static %}

{% block titulo_conteudo %}Atualizações {% endblock %}

{% block opcoes %}
	
{% endblock %}

{% block conteudo %}			
	<div class="container-fluid">
		<div class="row">
			<form method="get" action="#">
		        <div class="col-sm-3">
			          <div class="form-group">
			          	<label>Tabela</label>
						<input type="text" name="tabela" value="{{nomeTabela}}" class="form-control xs" placeholder="Nome da tabela">
			          </div>
		        </div>
		        <div class="col-sm-2">
			          <div class="form-group">
			          	<label>Atualizada após</label>
			            <input type="date" name="data" value="{{data}}" class="form-control xs">
			          </div>
		        </div>
		        <div class="col-sm-3">
		        	<div class="form-group">
		        		<br>
			            <input type="submit" value="buscar" class="btn btn-primary">
			         </div>
		        </div>
	        </form>
	    </div>
		<div class="table-responsive">
			{% if atualizacoes|length > 0 %}
				<table id="tabela-produtos" class="table  table-striped  table-bordered  table-hover  table-condensed  js-sticky-table">
					<thead class="aw-table-header-dark"><!--thead-dark-->
						<tr>
							<th>Tabela</th>
							<th>Data atualização</th>
							<th>Mês_Ref</th>
							<th>Ano_Ref</th>
							<th>Responsável</th>
							<th class="text-center">Editar</th>
							<th class="text-center">Excluir</th>
						</tr>
					</thead>				  
					<tbody>
						{% for atualizacao in atualizacoes %}
							<tr >
								<td data-toggle="tooltip" data-placement="top" title='Detalhes da atualização'>
									<a href="{% url 'gestorbases:detalhes_atualizacao' pk=atualizacao.id %}">{{atualizacao.tabela}}</a>
								</td>
								<td >
									{{atualizacao.data_atualizacao}}
								</td>

								<td class="text-left">{{atualizacao.mes_ref}}</td>

								<td class="text-center">{{atualizacao.ano_ref}}</td>

								<td class="text-center">{{atualizacao.responsavel}}</td>

								<td class="text-center">
									<a href="{% url 'gestorbases:atualiza_atualizacao' pk=atualizacao.pk %}" class="btn btn-info btn-xs"><span class="fa fa-edit"></span>
							        </a>
							    </td>
							    <td class="text-center">
							    	<form>
									<!--<button type="button" class="btn btn-danger btn-xs"> <!--onclick="excluir()"-->
										<a href="{% url 'gestorbases:exclui_atualizacao' pk=atualizacao.pk %}" class="btn btn-danger btn-xs">
										<span class="fa fa-trash" ></span>
										</a>
									</form>
								</td>
							</tr>
						{% endfor %}
					</tbody>
				</table>
			{% else %}
                <div class="text-center mt-5 mb-5 jumbotron">
                   <h5>Nenhuma <code>Base</code> cadastrada ainda.</h5>
                </div>
            {% endif %}
		</div>

    	<hr style="margin-top: : 0px">
    	<div class="row">
			<!-- CONTROLES DE NAVEGAÇÃO -->
			<div class="col-sm-9 col-md-6 col-lg-8">
				<ul class="pagination">
					{% for atualizacao in atualizacoes.paginator.page_range %}
						
						<li class="{% if  atualizacao  ==  atualizacoes.number  %}active{% endif %}" ><a href="?page={{atualizacao}}">{{atualizacao}}</a></li>
					{% endfor %}
				
				</ul>
			</div>

			<div class="col-sm-3 col-md-6 col-lg-4 text-right">
				<div> <!-- class="text-right" 
			        <a href="#" class="btn btn-primary">
			          Nova Atualização
			        </a>
			        -->
		    	</div>
	    	</div>

    	</div>
	</div>

{% endblock %}

myproject/gestorbases/templates/gestorbases/atualizacao/teste.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

{% comment %}
{% for tab in tabelas %}
	{{tab.nome}}
{% endfor %}
{% endcomment %}

<br>
<br>


{{ condicao }}

<br>
<br>
{% comment %}
{% for at in atualizacoes %}
	{{ at }}

{% endfor %}
{% endcomment %}

</body>
</html>